import { NextRequest, NextResponse } from 'next/server'
import { anthropic, AGENT_PROMPTS } from '@/lib/claude'
import { createServerClient } from '@/lib/supabase'

const GITHUB_TOKEN = process.env.GITHUB_TOKEN
const GITHUB_ORG = process.env.GITHUB_ORG || 'increative-websites'
const VERCEL_TOKEN = process.env.VERCEL_TOKEN
const VERCEL_TEAM_ID = process.env.VERCEL_TEAM_ID

interface WebsiteFile {
  [path: string]: string
}

interface GeneratedProject {
  projectName: string
  description: string
  files: WebsiteFile
}

// Generate website code using Claude
async function generateWebsite(brief: string, existingUrl?: string): Promise<GeneratedProject> {
  const taskPrompt = existingUrl
    ? `Udělej redesign webu ${existingUrl}.

Zadání od klienta:
${brief}

Analyzuj současný web a vytvoř moderní redesign.`
    : `Vytvoř nový web podle tohoto zadání:

${brief}`

  const response = await anthropic.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 8192,
    system: AGENT_PROMPTS.web_developer,
    messages: [
      {
        role: 'user',
        content: `${taskPrompt}

Vytvoř kompletní Next.js projekt s Tailwind CSS. Zahrň:
- package.json s potřebnými dependencies
- tailwind.config.js
- app/layout.tsx
- app/page.tsx
- app/globals.css
- Všechny další potřebné komponenty

DŮLEŽITÉ: Odpověz POUZE validním JSON objektem bez markdown formátování.`,
      },
    ],
  })

  const outputText = response.content[0].type === 'text' ? response.content[0].text : ''

  // Parse JSON from response (handle potential markdown code blocks)
  let jsonStr = outputText
  const jsonMatch = outputText.match(/```(?:json)?\s*([\s\S]*?)```/)
  if (jsonMatch) {
    jsonStr = jsonMatch[1]
  }

  try {
    return JSON.parse(jsonStr.trim())
  } catch {
    // If parsing fails, create a basic structure from the text
    throw new Error('Nepodařilo se vygenerovat projekt. Zkuste to znovu.')
  }
}

// Create GitHub repository
async function createGitHubRepo(projectName: string, description: string): Promise<string> {
  if (!GITHUB_TOKEN) {
    throw new Error('GitHub token není nakonfigurován')
  }

  const response = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${GITHUB_TOKEN}`,
      'Accept': 'application/vnd.github+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      name: projectName,
      description,
      private: false,
      auto_init: false,
    }),
  })

  if (!response.ok) {
    const error = await response.json()
    if (error.errors?.[0]?.message?.includes('already exists')) {
      // Repo exists, return its URL
      const userResponse = await fetch('https://api.github.com/user', {
        headers: { 'Authorization': `Bearer ${GITHUB_TOKEN}` }
      })
      const user = await userResponse.json()
      return `https://github.com/${user.login}/${projectName}`
    }
    throw new Error(`GitHub: ${error.message || 'Nepodařilo se vytvořit repozitář'}`)
  }

  const repo = await response.json()
  return repo.html_url
}

// Push files to GitHub
async function pushToGitHub(repoUrl: string, files: WebsiteFile): Promise<void> {
  if (!GITHUB_TOKEN) {
    throw new Error('GitHub token není nakonfigurován')
  }

  // Extract owner and repo from URL
  const match = repoUrl.match(/github\.com\/([^/]+)\/([^/]+)/)
  if (!match) throw new Error('Neplatná URL repozitáře')
  const [, owner, repo] = match

  // Create tree entries
  const treeEntries = Object.entries(files).map(([path, content]) => ({
    path,
    mode: '100644' as const,
    type: 'blob' as const,
    content,
  }))

  // Create tree
  const treeResponse = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/trees`, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${GITHUB_TOKEN}`,
      'Accept': 'application/vnd.github+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      tree: treeEntries,
    }),
  })

  if (!treeResponse.ok) {
    throw new Error('Nepodařilo se vytvořit soubory na GitHubu')
  }

  const tree = await treeResponse.json()

  // Create commit
  const commitResponse = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/commits`, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${GITHUB_TOKEN}`,
      'Accept': 'application/vnd.github+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      message: 'Initial commit - generated by FSA Web Developer',
      tree: tree.sha,
    }),
  })

  if (!commitResponse.ok) {
    throw new Error('Nepodařilo se vytvořit commit')
  }

  const commit = await commitResponse.json()

  // Update main branch reference
  const refResponse = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs/heads/main`, {
    method: 'PATCH',
    headers: {
      'Authorization': `Bearer ${GITHUB_TOKEN}`,
      'Accept': 'application/vnd.github+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      sha: commit.sha,
      force: true,
    }),
  })

  // If main doesn't exist, create it
  if (!refResponse.ok) {
    await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${GITHUB_TOKEN}`,
        'Accept': 'application/vnd.github+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        ref: 'refs/heads/main',
        sha: commit.sha,
      }),
    })
  }
}

// Deploy to Vercel
async function deployToVercel(projectName: string, repoUrl: string): Promise<string> {
  if (!VERCEL_TOKEN) {
    throw new Error('Vercel token není nakonfigurován')
  }

  // Extract owner and repo from URL
  const match = repoUrl.match(/github\.com\/([^/]+)\/([^/]+)/)
  if (!match) throw new Error('Neplatná URL repozitáře')
  const [, owner, repo] = match

  // Create Vercel project
  const projectResponse = await fetch('https://api.vercel.com/v10/projects', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${VERCEL_TOKEN}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      name: projectName,
      framework: 'nextjs',
      gitRepository: {
        type: 'github',
        repo: `${owner}/${repo}`,
      },
      ...(VERCEL_TEAM_ID && { teamId: VERCEL_TEAM_ID }),
    }),
  })

  if (!projectResponse.ok) {
    const error = await projectResponse.json()
    // If project exists, trigger a new deployment
    if (error.error?.code === 'PROJECT_EXISTS') {
      // Trigger deployment
      const deployResponse = await fetch('https://api.vercel.com/v13/deployments', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${VERCEL_TOKEN}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          name: projectName,
          gitSource: {
            type: 'github',
            repo: `${owner}/${repo}`,
            ref: 'main',
          },
          ...(VERCEL_TEAM_ID && { teamId: VERCEL_TEAM_ID }),
        }),
      })

      if (deployResponse.ok) {
        const deployment = await deployResponse.json()
        return `https://${deployment.url || `${projectName}.vercel.app`}`
      }
      return `https://${projectName}.vercel.app`
    }
    throw new Error(`Vercel: ${error.error?.message || 'Nepodařilo se vytvořit projekt'}`)
  }

  const project = await projectResponse.json()
  return `https://${project.name}.vercel.app`
}

export async function POST(request: NextRequest) {
  const supabase = createServerClient()
  let taskId: string | null = null
  let dbError: string | null = null

  try {
    const body = await request.json()
    const { title, description, clientName, existingUrl, priority = 'medium' } = body

    // STEP 0: Save task IMMEDIATELY with 'processing' status
    try {
      const { data: newTask, error } = await supabase.from('tasks').insert({
        type: 'web_development',
        title,
        description,
        status: 'processing',
        priority,
        client_name: clientName || null,
        agent_type: 'web_developer',
        output: 'Generuji web...',
        metadata: { existingUrl },
      }).select('id').single()

      if (error) {
        console.error('Failed to create task:', error)
        dbError = `DB Error: ${error.message}`
      } else {
        taskId = newTask.id
      }
    } catch (dbErr) {
      console.error('Failed to save task to database:', dbErr)
      dbError = `DB Exception: ${dbErr instanceof Error ? dbErr.message : 'Unknown'}`
    }

    // If we couldn't save the task, return error immediately
    if (!taskId) {
      return NextResponse.json({
        success: false,
        error: dbError || 'Nepodařilo se uložit úkol do databáze. Zkontrolujte SUPABASE_SERVICE_ROLE_KEY.',
      }, { status: 500 })
    }

    // Step 1: Generate website code
    const project = await generateWebsite(description, existingUrl)

    // Sanitize project name for GitHub/Vercel
    const sanitizedName = project.projectName
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '-')
      .replace(/-+/g, '-')
      .substring(0, 50)

    let githubUrl = ''
    let vercelUrl = ''

    // Step 2: Create GitHub repo and push code
    if (GITHUB_TOKEN) {
      try {
        githubUrl = await createGitHubRepo(sanitizedName, project.description)
        await pushToGitHub(githubUrl, project.files)
      } catch (error) {
        console.error('GitHub error:', error)
        // Continue without GitHub
      }
    }

    // Step 3: Deploy to Vercel
    if (VERCEL_TOKEN && githubUrl) {
      try {
        vercelUrl = await deployToVercel(sanitizedName, githubUrl)
      } catch (error) {
        console.error('Vercel error:', error)
        // Continue without Vercel
      }
    }

    // Build output summary
    const output = `# ${project.projectName}

${project.description}

## Odkazy
${githubUrl ? `- **GitHub**: ${githubUrl}` : '- GitHub: Není nakonfigurován (nastavte GITHUB_TOKEN)'}
${vercelUrl ? `- **Web**: ${vercelUrl}` : '- Vercel: Není nakonfigurován (nastavte VERCEL_TOKEN)'}

## Vygenerované soubory
${Object.keys(project.files).map(f => `- \`${f}\``).join('\n')}

## Další kroky
1. ${vercelUrl ? `Zkontrolujte web na ${vercelUrl}` : 'Nasaďte projekt na Vercel'}
2. Připojte vlastní doménu
3. Nastavte analytics a monitoring`

    const finalStatus = vercelUrl ? 'completed' : 'needs_review'

    // STEP 4: Update task with result
    if (taskId) {
      await supabase.from('tasks').update({
        status: finalStatus,
        output,
        metadata: {
          projectName: project.projectName,
          githubUrl,
          vercelUrl,
          files: Object.keys(project.files),
        },
      }).eq('id', taskId)
    }

    return NextResponse.json({
      success: true,
      status: finalStatus,
      taskId,
      projectName: project.projectName,
      githubUrl,
      vercelUrl,
      output,
      files: project.files,
    })
  } catch (error) {
    console.error('Web Developer API Error:', error)

    // Update task as failed if we have taskId
    if (taskId) {
      await supabase.from('tasks').update({
        status: 'failed',
        output: `Chyba: ${error instanceof Error ? error.message : 'Neznámá chyba'}`,
      }).eq('id', taskId)
    }

    return NextResponse.json(
      {
        success: false,
        taskId,
        error: error instanceof Error ? error.message : 'Neznámá chyba',
      },
      { status: 500 }
    )
  }
}
